var poi = {
"type": "FeatureCollection",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
                                                                                
"features": [


{ "type": "Feature", "properties": { "id": "CCPH1", "nom": "Eglise Saint Jacques et Saint Christophe", "descriptif": null, "tel": null, "mail": null, "site_web": "", "sous_cat": "Patrimoine religieux", "categorie": "Patrimoine Bâti", "adresse": null, "adresse2": "", "cp": null, "commune": null, "photo": null, "source": "" }, "geometry": { "type": "Point", "coordinates": [ 1.60153722363022,48.78942612874243 ] } },


{ "type": "Feature", "properties": { "id": "CCPH2", "nom": "Croix Saint Jacques", "descriptif": "<Div Align=Justify>Cette croix dut érigée pour rendre hommage aux pèlerins partis de Houdan pout Montserrat, en Catalogne, en 1582, probablement pour invoquer Notre Damede Montserrat afin que cesse le fléau de la Peste qui sévissait à l'époque.</Div>", "tel": null, "mail": null, "site_web": "", "sous_cat": "Patrimoine religieux", "categorie": "Patrimoine Bâti", "adresse": null, "adresse2": "", "cp": null, "commune": null, "photo": "https://cdn.pixabay.com/photo/2016/11/27/20/43/golgotha-1863767_1280.png", "source": "" }, "geometry": { "type": "Point", "coordinates": [ 1.5984386469122216 ,48.78458531209732] } },

{ "type": "Feature", "properties": { "id": "CCPH3", "nom": "Hôpital de Houdan", "descriptif": "<Div Align=Justify>Une léproserie fut installée au milieu du XIIème siècle au nord de la Ville, au-delà du pont de chemin de fer. La lèpre ayant disparu de nos régions, la léproserie ferma en 1560. Elle fut remplacée par l'Hôtel-Dieu qui fut bâti sur l'emplacement de l'hôpital actuel. Il fonctionnera à partir de 1695 et sera utilisé jusqu'à la fin du XIXème siècle. Trop vétuste, il sera remplacé par le nouveau bâtiment inauguré en 1914.</Div>", "tel": null, "mail": null, "site_web": "", "sous_cat": "Santé", "categorie": "Patrimoine Bâti", "adresse": null, "adresse2": "", "cp": null, "commune": null, "photo": "", "source": "" }, "geometry": { "type": "Point", "coordinates": [  1.60022288476321,48.792931930545244] } },

{ "type": "Feature", "properties": { "id": "CCPH4", "nom": "Eglise Saint Germain", "descriptif": null, "tel": null, "mail": null, "site_web": "", "sous_cat": "Patrimoine religieux", "categorie": "Patrimoine Bâti", "adresse": null, "adresse2": "", "cp": null, "commune": null, "photo": null, "source": "" }, "geometry": { "type": "Point", "coordinates": [1.6616198879794124,48.74245889058121 ] } },

{ "type": "Feature", "properties": { "id": "CCPH5", "nom": "Hôtel Hapy Houdan 78", "descriptif": null, "tel": null, "mail": "reservation@hotel-hapy.com", "site_web": "www.hotel-hapy.com/", "sous_cat": "Hotel", "categorie": "Hébergement", "adresse": null, "adresse2": "", "cp": null, "commune": null, "photo": null, "source": "" }, "geometry": { "type": "Point", "coordinates": [ 1.5924216194542387,48.79208519011008 ] } },



{ "type": "Feature", "properties": { "id": "CCPH6", "nom": "Chomalee", "descriptif": "<Div Align=Center>restauration thaïlandaise</Div>", "tel": null, "mail": null, "site_web": "https://chomalee-restaurant-houdan.eatbu.com/?lang=fr", "sous_cat": "Restaurant", "categorie": "Restaurants-Marchés-Terroir", "adresse": null, "adresse2": "", "cp": null, "commune": null, "photo": null, "source": "" }, "geometry": { "type": "Point", "coordinates": [ 1.60184622171726,48.79563034818086 ] } },

{ "type": "Feature", "properties": { "id": "CCPH7", "nom": "Eglise Saint Rémi", "descriptif": null, "tel": null, "mail": "", "site_web": "", "sous_cat": "Patrimoine religieux", "categorie": "Patrimoine Bâti", "adresse": null, "adresse2": "", "cp": null, "commune": null, "photo": null, "source": "" }, "geometry": { "type": "Point", "coordinates": [ 1.5389661992972539,48.713056377258624  ] } },

{ "type": "Feature", "properties": { "id": "CCPH8", "nom": "Office du Tourisme", "descriptif": null, "tel": "01 30 59 53 86", "mail": "contact@tourismepayshoudanais.fr", "site_web": "http://www.tourisme-pays-houdanais.fr", "sous_cat": "Office du Tourisme", "categorie": "Informations", "adresse": null, "adresse2": "", "cp": null, "commune": null, "photo": null, "source": "" }, "geometry": { "type": "Point", "coordinates": [1.5991827727741197,48.789275138923216  ] } },

{ "type": "Feature", "properties": { "id": "CCPH9", "nom": "Marché D'Adainville", "descriptif": "<Div Align=Justify>Tous les vendredis de 16h à 20h sur le parking de la Mairie, retrouvez un primeur avec ses produits locaux, de saison, labellisés agriculture biologique (fruits, légumes, champignong, fromages, jus et confitures...). Un second marché avec plus d exposants est également proposé à Adainville, un vendredi par mois (généralement le premier vendredi de chaque mois).</Div>", "tel": "", "mail": "", "site_web": "", "sous_cat": "Marchés", "categorie": "Restaurants-Marchés-Terroir", "adresse": null, "adresse2": "", "cp": null, "commune": null, "photo": null, "source": "" }, "geometry": { "type": "Point", "coordinates": [1.6528539906857291 ,48.72265938094551] } },

{ "type": "Feature", "properties": { "id": "CCPH10", "nom": "Marché D'Houdan", "descriptif": "<Div Align=Justify>Le marché de Houdan vous accueille tous les vendredis matin, rue d'Epernon à partir de l’arrière de l’église jusqu’au carrefour devant l’école. Pour la tranquillité des promeneurs, la rue d’Epernon est fermée à la circulation et au stationnement de 5h00 à 15h00 ce jour-là.</Div>", "tel": "", "mail": "", "site_web": "", "sous_cat": "Marchés", "categorie": "Restaurants-Marchés-Terroir", "adresse": null, "adresse2": "", "cp": null, "commune": null, "photo": null, "source": "" }, "geometry": { "type": "Point", "coordinates": [1.6023307754912366,48.78874821229571] } },

{ "type": "Feature", "properties": { "id": "CCPH11", "nom": "Eglise Saint Martin", "descriptif": null, "tel": null, "mail": "", "site_web": "", "sous_cat": "Patrimoine religieux", "categorie": "Patrimoine Bâti", "adresse": null, "adresse2": "", "cp": null, "commune": null, "photo": null, "source": "" }, "geometry": { "type": "Point", "coordinates": [  1.6630787385129082,48.756760448877806  ] } },

{ "type": "Feature", "properties": { "id": "CCPH12", "nom": "Eglise Saint Martin", "descriptif": null, "tel": null, "mail": "", "site_web": "", "sous_cat": "Patrimoine religieux", "categorie": "Patrimoine Bâti", "adresse": null, "adresse2": "", "cp": null, "commune": null, "photo": null, "source": "" }, "geometry": { "type": "Point", "coordinates": [ 1.6183825884026466,48.90324418733792 ] } },

{ "type": "Feature", "properties": { "id": "CCPH13", "nom": "La Fraiserie de Houdan", "descriptif": "Vente directe à la ferme le lundi, le mercredi et le vendredi de 16h à 19h, le samedi de 10h à 12h et de 16h à 19h, seulement en mai et en juin. Vente directe à la Place de la Gare 78640 Villiers-Saint-Fréderic le mardi et le jeudi de 16h à 19h, sur le quai de la gare SNCF. La Fraiseraie de Houdan propose à la vente directe des fraises, mais également des légumes (selon saison) : tomates, poivrons, herbes aromatiques, salades, concombres, courgettes, haricots verts, courges... Contact et réservation par mail (voir ci-dessus), à retirer avant 18h30.", "tel": null, "mail": "lafraiseraiedehoudan@gmail.com", "site_web": "", "sous_cat": "Fruits et Légumes", "categorie": "Restaurants-Marchés-Terroir", "adresse": null, "adresse2": "", "cp": null, "commune": null, "photo": null, "source": "" }, "geometry": { "type": "Point", "coordinates": [ 1.5775430743671122,48.787071701423834 ] } },

{ "type": "Feature", "properties": { "id": "CCPH14", "nom": "EARL FERME LECOQ", "descriptif": "Vente à la ferme et ventes sur les marchés de Mantes-La-Jolie, Meulan..etc de poulets, pintades, canards, lapins, œufs, rillettes de poules maison et miel du hameau. Comme la plupart des fermes du XVIe siècle, cette exploitation a accueilli pendant 400 ans des animaux aussi variés que des vaches, des cochons, des poules, des moutons et des chevaux. Depuis deux générations, y sont élevés des poulets, des pintades, des lapins, des canards et des poules pondeuses. Pour les fêtes de fin d année, la ferme éleve des chapons, des dindes, des poulardes et des oies. Elle posséde 35 hectares de cultures de blé, de mais, d orge et de féverole qui servent à nourrir traditionnellement les animaux. Les bêtes sont élevées au sol, et sont libres de sortir dans leur pré. La Ferme Lecoq vend tous ses produits prêts à cuire sous le marché couvert de Mantes la Jolie, sur le marché extérieur de Meulan et à la boutique de la Ferme.", "tel": null, "mail": "", "site_web": "http://fermelecoq.blogspot.fr/", "sous_cat": "Fruits et Légumes", "categorie": "Restaurants-Marchés-Terroir", "adresse": null, "adresse2": "", "cp": null, "commune": null, "photo": null, "source": "" }, "geometry": { "type": "Point", "coordinates": [ 1.579819957912611,48.93208857560287 ] } },

{ "type": "Feature", "properties": { "id": "CCPH15", "nom": "La Brasserie de la Vaucouleurs", "descriptif": null, "tel": "09 70 66 72 72", "mail": "", "site_web": "https://www.facebook.com/brasseriedelavaucouleurs/", "sous_cat": "Restaurant", "categorie": "Restaurants-Marchés-Terroir", "adresse": null, "adresse2": "", "cp": null, "commune": null, "photo": "https://scontent-cdg4-2.xx.fbcdn.net/v/t39.30808-6/275441200_107350211908893_4049152345791539704_n.jpg?_nc_cat=109&ccb=1-7&_nc_sid=5f2048&_nc_ohc=XXkghxL7e4MAX9c_Rrg&_nc_ht=scontent-cdg4-2.xx&oh=00_AfBBI4v56uvOEgHkvOoJY58V9AssTORErWxh-_3qYijpfw&oe=65614834", "source": "" }, "geometry": { "type": "Point", "coordinates": [ 1.618565398720536 , 48.8737234720169 ] } },

{ "type": "Feature", "properties": { "id": "CCPH16", "nom": "Les écuries de l'Orée du Bois", "descriptif": "Petite écurie conviviale située dans un cadre paisible et verdoyant, l'équipe des écuries de l'Orée du Bois accueille les plus petits dès 6 ans au poney-Club et propose également des animations toute l'année : stages, randonnées, pony-games, équifun... Un Club House est par ailleurs à disposition des cavaliers.", "tel": "01 30 93 42 12", "mail": "", "site_web": "https://www.poney-club-septeuil.fr/presentation", "sous_cat": "Equitation", "categorie": "Loisirs", "adresse": null, "adresse2": "", "cp": null, "commune": null, "photo": "https://scontent-cdg4-2.xx.fbcdn.net/v/t39.30808-6/275441200_107350211908893_4049152345791539704_n.jpg?_nc_cat=109&ccb=1-7&_nc_sid=5f2048&_nc_ohc=XXkghxL7e4MAX9c_Rrg&_nc_ht=scontent-cdg4-2.xx&oh=00_AfBBI4v56uvOEgHkvOoJY58V9AssTORErWxh-_3qYijpfw&oe=65614834", "source": "" }, "geometry": { "type": "Point", "coordinates": [ 1.6670155175878052,48.906182666904 ] } },

{ "type": "Feature", "properties": { "id": "CCPH17", "nom": "Lilac Cottage", "descriptif": "Très bien situé, proche de Houdan, au sein d'une longère, ancien corps de ferme du 18ème siècle, dans un hameau tranquille aux murs en pierre de silex en pleine campagne.", "tel": null, "mail": "fabrice.pl@wanadoo.fr", "site_web": "http://www.lilaccottage.fr/", "sous_cat": "Gites", "categorie": "Hébergement", "adresse": null, "adresse2": "", "cp": null, "commune": null, "photo": "https://www.tourisme-pays-houdanais.fr/uploads/_ccph/ani_fichiers/lilac-cottage-ext_1_500px.jpg", "source": "" }, "geometry": { "type": "Point", "coordinates": [ 1.5568590207917352,48.81454428851419] } },

{ "type": "Feature", "properties": { "id": "CCPH18", "nom": "O'Plateau", "descriptif": "burgers, poké bowl, etc.<br> Le Mardi de de 19h00 à 22h00 <br> 06 69 10 72 84", "tel": null, "mail": "", "site_web": "https://www.o-plateau.com/?fbclid=IwAR1qqjZdRXd7HTQGLpxRZLzgsNgwrtJ5rULH5fcX727mSZHcuRGi67fZ_xA", "sous_cat": "Food Trucks", "categorie": "Restaurants-Marchés-Terroir", "adresse": null, "adresse2": "", "cp": null, "commune": null, "photo": "", "source": "" }, "geometry": { "type": "Point", "coordinates": [ 1.6609931807862408,48.74233529829903] } },

{ "type": "Feature", "properties": { "id": "CCPH19", "nom": "Domaine de la Christinière", "descriptif": "En lisière de la forêt de Rambouillet, cette propriété entièrement rénovée est un lieu unique, paisible et élégant qui répondra à tous vos projets de séjours en famille ou entre amis.<br> Sur plus de 50 hectares de forêt et de prairies, découvrez cette ancienne ferme composée d'une grande maison de maitre très confortable de 6 chambres, d'une maison d'amis de 5 chambres et d'un camp aventure pour une expérience unique en pleine nature. <br>Vous avez accès au parc attenant.", "tel": null, "mail": "domainelachristiniere@gmail.com", "site_web": "https://www.domainelachristiniere.fr", "sous_cat": "Gites", "categorie": "Hébergement", "adresse": null, "adresse2": "", "cp": null, "commune": null, "photo": "", "source": "" }, "geometry": { "type": "Point", "coordinates": [ 1.6755479982058403,48.736384882400806] } },

{ "type": "Feature", "properties": { "id": "CCPH20", "nom": "le Gardon Dammartinois", "descriptif": "Situé dans un domaine privé, la Mare au Prévost, le Gardon Dammartinois propose de la pêche au coup de gardons, tanches, carpes, carassins et poissons rouges.<br>Des cartes de pêches sont en vente au café des sports de Dammartin.", "tel": "01 30 42 55 94", "mail": "", "site_web": "", "sous_cat": "Pêche", "categorie": "Loisirs", "adresse": null, "adresse2": "", "cp": null, "commune": null, "photo": "", "source": "" }, "geometry": { "type": "Point", "coordinates": [1.609880072876289,48.90790011452388] } },

{ "type": "Feature", "properties": { "id": "CCPH21", "nom": "les étangs de Maintion", "descriptif": "Situés entre Bourdonné et Condé-sur-Vesgre, les étangs de Maintion regroupent 4 bassins pour la pêche à la truite dans un cadre verdoyant et très calme, idéal pour la pêche. Sur place, vous trouverez un barbecue pour égayer votre repas lors des journées pêche et un abri couvert en cas de mauvais temps.", "tel": "06 87 26 31 10", "mail": "", "site_web": "http://etangsdemaintion.canalblog.com/", "sous_cat": "Pêche", "categorie": "Loisirs", "adresse": null, "adresse2": "", "cp": null, "commune": null, "photo": "", "source": "" }, "geometry": { "type": "Point", "coordinates": [1.6585180778608897,48.74728085601541] } },

{ "type": "Feature", "properties": { "id": "CCPH22", "nom": "Galop'Âne ", "descriptif": "L'association Galop'Âne propose des balades en ânes, et organise ou participe à de nombreuses animations autour de l'âne. Elle peut également intervenir pour vos événements comme des mariages. Elle organise par ailleurs 2 randonnées par an dans la région, ouvertes à tous.", "tel": "01 30 42 52 87", "mail": "", "site_web": "https://www.facebook.com/galopane", "sous_cat": "Balade avec des Anes", "categorie": "Loisirs", "adresse": null, "adresse2": "", "cp": null, "commune": null, "photo": "", "source": "" }, "geometry": { "type": "Point", "coordinates": [1.615393798302975,48.90216872893175] } },

{ "type": "Feature", "properties": { "id": "CCPH23", "nom": "Site Archéologique de Septeuil ", "descriptif": "LORS DES TRAVAUX DE LA DÉVIATION DE LA RD 983 À SEPTEUIL EN 1984 ON A DÉCOUVERT AU LIEU-DIT LA FÉÉRIE UN SANCTUAIRE DES EAUX DE L’ÉPOQUE GALLO-ROMAINE DATÉ DU 1ER AU IVE SIÈCLES CONSTRUIT SUR LA RÉSURGENCE D’UNE SOURCE. DES REPRÉSENTATIONS DU DIEU MYTHRA Y FURENT DÉCOUVERTES. <br>Il s’agit d’un bâtiment rectangulaire dont les  parois sont recouvertes de plaques de  calcaires et de marbre blanc ayant en son centre un bassin .La pièce sacrée, la cella, comportait  sur le mur situé face à l’entrée une niche dans laquelle se trouvait une nymphe allongée versant l’eau d’une hydrie, qui se répandait ensuite dans le bassin. Une copie a été placée au même endroit. La statue en marbre de Carrare est au musée de Saint Germain en Laye. Devant cette découverte exceptionnelle, le Conseil général des Yvelines a financé la construction d’une restitution de ce sanctuaire de source (ainsi qu’un moulage de la statue). Lors de la restitution du site, afin de permettre les visites,  il fallut déplacer tout le sanctuaire  de quelques mètres pour éviter qu’il ne soit à nouveau envasé par la Vaucouleurs. Un parking et des tableaux explicatifs jouxtent le monument qui est ouvert au public toute l’année.", "tel": "", "mail": "", "site_web": "", "sous_cat": "Musée", "categorie": "Patrimoine Bâti", "adresse": null, "adresse2": "", "cp": null, "commune": null, "photo": "", "source": "" }, "geometry": { "type": "Point", "coordinates": [ 1.671338586354414,48.89786290637316] } },

{ "type": "Feature", "properties": { "id": "CCPH24", "nom": "Eglise Saint Pierre", "descriptif": null, "tel": null, "mail": "", "site_web": "", "sous_cat": "Patrimoine religieux", "categorie": "Patrimoine Bâti", "adresse": null, "adresse2": "", "cp": null, "commune": null, "photo": null, "source": "" }, "geometry": { "type": "Point", "coordinates": [ 1.703060942026681,48.82890788588473] } },

{ "type": "Feature", "properties": { "id": "CCPH25", "nom": "Eglise Saint Cloud", "descriptif": null, "tel": null, "mail": "", "site_web": "", "sous_cat": "Patrimoine religieux", "categorie": "Patrimoine Bâti", "adresse": null, "adresse2": "", "cp": null, "commune": null, "photo": null, "source": "" }, "geometry": { "type": "Point", "coordinates": [1.7159785712682332,48.86798420805839] } },

{ "type": "Feature", "properties": { "id": "CCPH26", "nom": "Eglise Saint-Sulpice", "descriptif": null, "tel": null, "mail": "", "site_web": "", "sous_cat": "Patrimoine religieux", "categorie": "Patrimoine Bâti", "adresse": null, "adresse2": "", "cp": null, "commune": null, "photo": null, "source": "" }, "geometry": { "type": "Point", "coordinates": [1.5552079285209695,48.823787150475376] } },

{ "type": "Feature", "properties": { "id": "CCPH27", "nom": "Château La Jaunière", "descriptif": "Château du 19ème siècle", "tel": null, "mail": "", "site_web": "", "sous_cat": "Patrimoine remarquable", "categorie": "Patrimoine Bâti", "adresse": null, "adresse2": "", "cp": null, "commune": null, "photo": null, "source": "" }, "geometry": { "type": "Point", "coordinates": [1.673209505774146,48.71876621959] } },

{ "type": "Feature", "properties": { "id": "CCPH28", "nom": "Château de Boinvilliers", "descriptif": "Vestiges du château", "tel": null, "mail": "", "site_web": "", "sous_cat": "Patrimoine remarquable", "categorie": "Patrimoine Bâti", "adresse": null, "adresse2": "", "cp": null, "commune": null, "photo": null, "source": "" }, "geometry": { "type": "Point", "coordinates": [ 1.662581715679405,48.919136088425816] } },

{ "type": "Feature", "properties": { "id": "CCPH29", "nom": "Château de Bourdonné", "descriptif": "Chaâteau du XVIIème siècle inscrit partiellement aux Monuments Historiques", "tel": null, "mail": "", "site_web": "", "sous_cat": "Patrimoine remarquable", "categorie": "Patrimoine Bâti", "adresse": null, "adresse2": "", "cp": null, "commune": null, "photo": null, "source": "" }, "geometry": { "type": "Point", "coordinates": [1.6583416515241776,48.7592758547022] } },

{ "type": "Feature", "properties": { "id": "CCPH30", "nom": "Château du Mesnils sur Opton", "descriptif": "Chaâteau du XVIIIème siècle", "tel": null, "mail": "", "site_web": "", "sous_cat": "Patrimoine remarquable", "categorie": "Patrimoine Bâti", "adresse": null, "adresse2": "", "cp": null, "commune": null, "photo": null, "source": "" }, "geometry": { "type": "Point", "coordinates": [1.6107692099957642,48.75184809236954] } },

{ "type": "Feature", "properties": { "id": "CCPH31", "nom": "Château de la Tournelle", "descriptif": "Château Belle Epoque", "tel": null, "mail": "", "site_web": "", "sous_cat": "Patrimoine remarquable", "categorie": "Patrimoine Bâti", "adresse": null, "adresse2": "", "cp": null, "commune": null, "photo": null, "source": "" }, "geometry": { "type": "Point", "coordinates": [1.666675762017835,48.89308411072315] } },

{ "type": "Feature", "properties": { "id": "CCPH32", "nom": "Château de Tilly", "descriptif": "", "tel": null, "mail": "", "site_web": "", "sous_cat": "Patrimoine remarquable", "categorie": "Patrimoine Bâti", "adresse": null, "adresse2": "", "cp": null, "commune": null, "photo": null, "source": "" }, "geometry": { "type": "Point", "coordinates": [1.5748305926719952,48.88257366305665] } },

{ "type": "Feature", "properties": { "id": "CCPH33", "nom": "Château de Corbeville", "descriptif": "", "tel": null, "mail": "", "site_web": "", "sous_cat": "Patrimoine remarquable", "categorie": "Patrimoine Bâti", "adresse": null, "adresse2": "", "cp": null, "commune": null, "photo": null, "source": "" }, "geometry": { "type": "Point", "coordinates": [1.704314921133236,48.879842987093774] } },

{ "type": "Feature", "properties": { "id": "CCPH34", "nom": "Château du Haut-Rosay", "descriptif": "", "tel": null, "mail": "", "site_web": "", "sous_cat": "Patrimoine remarquable", "categorie": "Patrimoine Bâti", "adresse": null, "adresse2": "", "cp": null, "commune": null, "photo": null, "source": "" }, "geometry": { "type": "Point", "coordinates": [1.6805595596711713,48.912675806810725] } },

{ "type": "Feature", "properties": { "id": "CCPH35", "nom": "Château de Richebourg", "descriptif": "", "tel": null, "mail": "", "site_web": "", "sous_cat": "Patrimoine remarquable", "categorie": "Patrimoine Bâti", "adresse": null, "adresse2": "", "cp": null, "commune": null, "photo": null, "source": "" }, "geometry": { "type": "Point", "coordinates": [1.6368432655734722,48.82425259709252] } },

{ "type": "Feature", "properties": { "id": "CCPH36", "nom": "Château des Ifs", "descriptif": "", "tel": null, "mail": "", "site_web": "", "sous_cat": "Patrimoine remarquable", "categorie": "Patrimoine Bâti", "adresse": null, "adresse2": "", "cp": null, "commune": null, "photo": null, "source": "" }, "geometry": { "type": "Point", "coordinates": [1.6951320248951829,48.840752159626426] } },


]
};